// samples.js
// Stacks v0.1.0
// Sample packages bundled as JS constants.
// These are the source of truth for the sample environments.
// The files in /environments/ are reference documentation and downloadable zips.
// When updating samples, update this file to match.

const STACKS_SAMPLES = [
  {
    id: "short-stories",
    name: "Short Stories",
    description: "Track short fiction by title, author, theme, and where you have it.",
    meta: {
      name: "Short Stories",
      version: "1.0.0",
      stacks_version: "0.1.0",
      exported_at: "",
      author: "",
    },
    schema: {
      name: "Short Stories",
      version: "1.0.0",
      id: "short-stories-v1",
      fields: [
        { id: "title",      name: "Title",      type: "string", required: true,  sortable: true  },
        { id: "author",     name: "Author",     type: "string", required: true,  sortable: true  },
        { id: "year",       name: "Year",       type: "number", required: false, sortable: true  },
        { id: "appears-in", name: "Appears In", type: "string", required: false, sortable: false },
        { id: "themes",     name: "Themes",     type: "list",   required: false, sortable: false },
        { id: "notes",      name: "Notes",      type: "string", required: false, sortable: false },
      ],
    },
    theme: {},
    data: {
      total_records: 2,
      last_updated: "2026-04-22T00:00:00Z",
      records: [
        {
          id: "abc123",
          schema_id: "short-stories-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "The Lottery",
            author: "Shirley Jackson",
            year: 1948,
            "appears-in": "The New Yorker, June 1948 · The Lottery and Other Stories (epub)",
            themes: ["ritual", "violence", "community", "conformity"],
            notes: "Devastating final paragraph.",
          },
          _warnings: [],
        },
        {
          id: "def456",
          schema_id: "short-stories-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "The Dead",
            author: "James Joyce",
            year: 1914,
            "appears-in": "Dubliners (epub) · The Portable James Joyce (paperback)",
            themes: ["memory", "mortality", "marriage", "Ireland"],
            notes: "Final lines are among the greatest in the language.",
          },
          _warnings: [],
        },
      ],
    },
    warnings: [],
  },

  {
    id: "music",
    name: "Music Collection",
    description: "Catalogue your vinyl, CDs, cassettes, and digital albums.",
    meta: {
      name: "Music Collection",
      version: "1.0.0",
      stacks_version: "0.1.0",
      exported_at: "",
      author: "",
    },
    schema: {
      name: "Music Collection",
      version: "1.0.0",
      id: "music-collection-v1",
      fields: [
        { id: "title",     name: "Title",     type: "string", required: true,  sortable: true  },
        { id: "artist",    name: "Artist",    type: "string", required: true,  sortable: true  },
        { id: "year",      name: "Year",      type: "number", required: false, sortable: true  },
        { id: "format",    name: "Format",    type: "string", required: false, sortable: true  },
        { id: "genre",     name: "Genre",     type: "list",   required: false, sortable: false },
        { id: "label",     name: "Label",     type: "string", required: false, sortable: false },
        { id: "condition", name: "Condition", type: "string", required: false, sortable: true  },
        { id: "notes",     name: "Notes",     type: "string", required: false, sortable: false },
      ],
    },
    theme: {},
    data: {
      total_records: 3,
      last_updated: "2026-04-22T00:00:00Z",
      records: [
        {
          id: "music001",
          schema_id: "music-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Kind of Blue",
            artist: "Miles Davis",
            year: 1959,
            format: "Vinyl",
            genre: ["jazz", "modal jazz"],
            label: "Columbia",
            condition: "Good",
            notes: "One of the best selling jazz albums of all time.",
          },
          _warnings: [],
        },
        {
          id: "music002",
          schema_id: "music-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Remain in Light",
            artist: "Talking Heads",
            year: 1980,
            format: "CD",
            genre: ["new wave", "art rock", "funk"],
            label: "Sire",
            condition: "Mint",
            notes: "Produced with Brian Eno.",
          },
          _warnings: [],
        },
        {
          id: "music003",
          schema_id: "music-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Dummy",
            artist: "Portishead",
            year: 1994,
            format: "Cassette",
            genre: ["trip-hop", "electronic"],
            label: "Go! Discs",
            condition: "Fair",
            notes: "Debut album. Glory Box is worth the price alone.",
          },
          _warnings: [],
        },
      ],
    },
    warnings: [],
  },

  {
    id: "movies",
    name: "Movie Collection",
    description: "Index your DVDs, Blu-rays, VHS tapes, and digital films.",
    meta: {
      name: "Movie Collection",
      version: "1.0.0",
      stacks_version: "0.1.0",
      exported_at: "",
      author: "",
    },
    schema: {
      name: "Movie Collection",
      version: "1.0.0",
      id: "movie-collection-v1",
      fields: [
        { id: "title",    name: "Title",    type: "string", required: true,  sortable: true  },
        { id: "director", name: "Director", type: "string", required: false, sortable: true  },
        { id: "year",     name: "Year",     type: "number", required: false, sortable: true  },
        { id: "format",   name: "Format",   type: "string", required: false, sortable: true  },
        { id: "rating",   name: "Rating",   type: "string", required: false, sortable: false },
        { id: "boxset",   name: "Boxset",   type: "string", required: false, sortable: true  },
        { id: "genre",    name: "Genre",    type: "list",   required: false, sortable: false },
        { id: "notes",    name: "Notes",    type: "string", required: false, sortable: false },
      ],
    },
    theme: {},
    data: {
      total_records: 3,
      last_updated: "2026-04-22T00:00:00Z",
      records: [
        {
          id: "movie001",
          schema_id: "movie-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "The 36th Chamber of Shaolin",
            director: "Lau Kar-leung",
            year: 1978,
            format: "Blu-ray",
            rating: "R",
            boxset: "Shawscope Vol. 2",
            genre: ["martial arts", "action"],
            notes: "One of the greatest kung fu films ever made.",
          },
          _warnings: [],
        },
        {
          id: "movie002",
          schema_id: "movie-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Stalker",
            director: "Andrei Tarkovsky",
            year: 1979,
            format: "DVD",
            rating: "PG",
            boxset: "",
            genre: ["science fiction", "drama"],
            notes: "Slow, hypnotic, essential.",
          },
          _warnings: [],
        },
        {
          id: "movie003",
          schema_id: "movie-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Robocop",
            director: "Paul Verhoeven",
            year: 1987,
            format: "VHS",
            rating: "R",
            boxset: "",
            genre: ["action", "science fiction", "satire"],
            notes: "Better than it has any right to be.",
          },
          _warnings: [],
        },
      ],
    },
    warnings: [],
  },

  {
    id: "games",
    name: "Video Game Collection",
    description: "Track your game library by platform, status, and condition.",
    meta: {
      name: "Video Game Collection",
      version: "1.0.0",
      stacks_version: "0.1.0",
      exported_at: "",
      author: "",
    },
    schema: {
      name: "Video Game Collection",
      version: "1.0.0",
      id: "games-collection-v1",
      fields: [
        { id: "title",     name: "Title",     type: "string", required: true,  sortable: true  },
        { id: "developer", name: "Developer", type: "string", required: false, sortable: true  },
        { id: "year",      name: "Year",      type: "number", required: false, sortable: true  },
        { id: "platform",  name: "Platform",  type: "string", required: false, sortable: true  },
        { id: "format",    name: "Format",    type: "string", required: false, sortable: false },
        { id: "genre",     name: "Genre",     type: "list",   required: false, sortable: false },
        { id: "condition", name: "Condition", type: "string", required: false, sortable: true  },
        { id: "status",    name: "Status",    type: "string", required: false, sortable: true  },
        { id: "notes",     name: "Notes",     type: "string", required: false, sortable: false },
      ],
    },
    theme: {},
    data: {
      total_records: 3,
      last_updated: "2026-04-22T00:00:00Z",
      records: [
        {
          id: "game001",
          schema_id: "games-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Disco Elysium",
            developer: "ZA/UM",
            year: 2019,
            platform: "PC",
            format: "Digital",
            genre: ["RPG", "detective"],
            condition: "",
            status: "Completed",
            notes: "One of the most original RPGs ever made.",
          },
          _warnings: [],
        },
        {
          id: "game002",
          schema_id: "games-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Castlevania: Symphony of the Night",
            developer: "Konami",
            year: 1997,
            platform: "PS1",
            format: "Physical",
            genre: ["action", "platformer", "metroidvania"],
            condition: "Good",
            status: "Completed",
            notes: "What is a man? A miserable little pile of secrets.",
          },
          _warnings: [],
        },
        {
          id: "game003",
          schema_id: "games-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Elden Ring",
            developer: "FromSoftware",
            year: 2022,
            platform: "PS5",
            format: "Physical",
            genre: ["action RPG", "soulslike", "open world"],
            condition: "Mint",
            status: "Playing",
            notes: "Send help.",
          },
          _warnings: [],
        },
      ],
    },
    warnings: [],
  },

  {
    id: "books",
    name: "Book Collection",
    description: "Catalogue your books by format, genre, and reading status.",
    meta: {
      name: "Book Collection",
      version: "1.0.0",
      stacks_version: "0.1.0",
      exported_at: "",
      author: "",
    },
    schema: {
      name: "Book Collection",
      version: "1.0.0",
      id: "book-collection-v1",
      fields: [
        { id: "title",     name: "Title",     type: "string", required: true,  sortable: true  },
        { id: "author",    name: "Author",    type: "string", required: true,  sortable: true  },
        { id: "year",      name: "Year",      type: "number", required: false, sortable: true  },
        { id: "genre",     name: "Genre",     type: "list",   required: false, sortable: false },
        { id: "format",    name: "Format",    type: "string", required: false, sortable: true  },
        { id: "publisher", name: "Publisher", type: "string", required: false, sortable: false },
        { id: "status",    name: "Status",    type: "string", required: false, sortable: true  },
        { id: "notes",     name: "Notes",     type: "string", required: false, sortable: false },
      ],
    },
    theme: {},
    data: {
      total_records: 3,
      last_updated: "2026-04-22T00:00:00Z",
      records: [
        {
          id: "book001",
          schema_id: "book-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Blood Meridian",
            author: "Cormac McCarthy",
            year: 1985,
            genre: ["literary fiction", "western", "historical"],
            format: "Paperback",
            publisher: "Random House",
            status: "Completed",
            notes: "The Judge is one of the great villains in American literature.",
          },
          _warnings: [],
        },
        {
          id: "book002",
          schema_id: "book-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "The Left Hand of Darkness",
            author: "Ursula K. Le Guin",
            year: 1969,
            genre: ["science fiction", "literary fiction"],
            format: "Epub",
            publisher: "Ace Books",
            status: "Completed",
            notes: "Changed how I think about gender, identity, and what science fiction can do.",
          },
          _warnings: [],
        },
        {
          id: "book003",
          schema_id: "book-collection-v1",
          created_at: "2026-04-22T00:00:00Z",
          updated_at: "2026-04-22T00:00:00Z",
          fields: {
            title: "Piranesi",
            author: "Susanna Clarke",
            year: 2020,
            genre: ["fantasy", "mystery"],
            format: "Hardcover",
            publisher: "Bloomsbury",
            status: "To Read",
            notes: "Everyone I trust has told me to read this.",
          },
          _warnings: [],
        },
      ],
    },
    warnings: [],
  },
];
